version: 2

models:
  - name: stg_accounts
    description: "Account table"
    columns:
      - name: account_id
        data_type: bigint
        description: ""

      - name: account_name
        data_type: string
        description: ""

      - name: account_type
        data_type: string
        description: ""

      - name: is_active
        data_type: bigint
        description: ""

      - name: created_at
        data_type: timestamp
        description: ""

      - name: updated_at
        data_type: timestamp
        description: ""